const UNSPLASH_KEY = "abcd1234";

const CLOUDINARY_API_KEY = 'abcd1234';
const CLOUDINARY_API_SECRET = 'abcd1234';
const CLOUDINARY_NAME = 'name1234';

const FACEBOOK_ID = 'abcd1234';  
const FACEBOOK_ACCESS_TOKEN = 'abcd1234';


module.exports.UNSPLASH_KEY = UNSPLASH_KEY;
module.exports.CLOUDINARY_NAME = CLOUDINARY_NAME;
module.exports.CLOUDINARY_API_KEY = CLOUDINARY_API_KEY;
module.exports.CLOUDINARY_API_SECRET = CLOUDINARY_API_SECRET;
module.exports.FACEBOOK_ID = FACEBOOK_ID;
module.exports.FACEBOOK_ACCESS_TOKEN = FACEBOOK_ACCESS_TOKEN;